# Generated by Django 3.2.5 on 2021-08-29 20:06

import careers.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_career_details', models.FileField(blank=True, null=True, upload_to='background/career_details/', validators=[careers.validators.validate_image_extension])),
                ('title', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('role_1', models.TextField(blank=True, null=True)),
                ('role_2', models.TextField(blank=True, null=True)),
                ('role_3', models.TextField(blank=True, null=True)),
                ('role_4', models.TextField(blank=True, null=True)),
                ('role_5', models.TextField(blank=True, null=True)),
                ('role_6', models.TextField(blank=True, null=True)),
                ('role_7', models.TextField(blank=True, null=True)),
                ('role_8', models.TextField(blank=True, null=True)),
                ('role_9', models.TextField(blank=True, null=True)),
                ('role_10', models.TextField(blank=True, null=True)),
                ('role_11', models.TextField(blank=True, null=True)),
                ('role_12', models.TextField(blank=True, null=True)),
                ('role_13', models.TextField(blank=True, null=True)),
                ('role_14', models.TextField(blank=True, null=True)),
                ('role_15', models.TextField(blank=True, null=True)),
                ('role_16', models.TextField(blank=True, null=True)),
                ('role_17', models.TextField(blank=True, null=True)),
                ('role_18', models.TextField(blank=True, null=True)),
                ('role_19', models.TextField(blank=True, null=True)),
                ('role_20', models.TextField(blank=True, null=True)),
                ('skill_1', models.TextField(blank=True, null=True)),
                ('skill_2', models.TextField(blank=True, null=True)),
                ('skill_3', models.TextField(blank=True, null=True)),
                ('skill_4', models.TextField(blank=True, null=True)),
                ('skill_5', models.TextField(blank=True, null=True)),
                ('skill_6', models.TextField(blank=True, null=True)),
                ('skill_7', models.TextField(blank=True, null=True)),
                ('skill_8', models.TextField(blank=True, null=True)),
                ('skill_9', models.TextField(blank=True, null=True)),
                ('skill_10', models.TextField(blank=True, null=True)),
                ('skill_11', models.TextField(blank=True, null=True)),
                ('skill_12', models.TextField(blank=True, null=True)),
                ('skill_13', models.TextField(blank=True, null=True)),
                ('skill_14', models.TextField(blank=True, null=True)),
                ('skill_15', models.TextField(blank=True, null=True)),
                ('skill_16', models.TextField(blank=True, null=True)),
                ('skill_17', models.TextField(blank=True, null=True)),
                ('skill_18', models.TextField(blank=True, null=True)),
                ('skill_19', models.TextField(blank=True, null=True)),
                ('skill_20', models.TextField(blank=True, null=True)),
                ('contract_duration', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('governorate', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=1, null=True)),
                ('job_shift', models.CharField(blank=True, choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=1, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('posted', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('minimum_education', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('minimum_experience', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('required_travel', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('no_of_jobs', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('deadline', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('puplished', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerDetatilImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_header_logo_sticky_career_detail_image', models.FileField(blank=True, null=True, upload_to='background/career_detail_image/', validators=[careers.validators.validate_image_extension])),
                ('image_footer_logo_career_detail_image', models.FileField(blank=True, null=True, upload_to='background/career_detail_image/', validators=[careers.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='CareerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_career_list', models.FileField(blank=True, null=True, upload_to='background/career_list/', validators=[careers.validators.validate_image_extension])),
            ],
        ),
    ]
