# Generated by Django 3.2.7 on 2021-09-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerdetail',
            name='image_career_details',
        ),
    ]
