# Generated by Django 3.2.7 on 2021-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20210930_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerdetail',
            name='role_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_10_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_1_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_2_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_3_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_4_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_5_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_6_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_7_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_8_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_9_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_10_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_1_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_2_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_3_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_4_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_5_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_6_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_7_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_8_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='skill_9_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
