# Generated by Django 3.2.7 on 2021-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_auto_20210930_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerdetail',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
