# Generated by Django 3.2.7 on 2021-09-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20210930_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerdetail',
            name='job_shift',
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
