# Generated by Django 3.2.5 on 2021-08-29 20:06

import django.core.validators
from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_middle_about', models.FileField(upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('text_about', models.TextField(blank=True, default='', max_length=1000)),
                ('text_about1', models.TextField(blank=True, default='', max_length=1000)),
                ('text_about2', models.TextField(blank=True, default='', max_length=1000)),
                ('text_about3', models.TextField(blank=True, default='', max_length=1000)),
                ('text_about4', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.             Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('region', models.CharField(choices=[('Baghdad', 'Baghdad'), ('Mousl', 'Mousl'), ('Erbil', 'Erbil'), ('Anbar', 'Anbar'), ('Babylon', 'Babylon'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Diyala', 'Diyala'), ('Dohuk', 'Dohuk'), ('Karbala', 'Karbala'), ('KirKuk', 'KirKuk'), ('Maysan', 'Maysan'), ('Najaf', 'Najaf'), ('Qaisiyah', 'Qaisiyah'), ('Salahaddin', 'Salahaddin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=12)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('english', models.CharField(blank=True, default='English', max_length=7, null=True)),
                ('kurdish', models.CharField(blank=True, default='Kurdish', max_length=7, null=True)),
                ('arabic', models.CharField(blank=True, default='Arabic', max_length=6, null=True)),
                ('cover_letter', models.TextField()),
                ('upload_cv', models.FileField(upload_to='uploadcv/', validators=[jobs.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.             Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_donate', models.FileField(upload_to='background/donate/', validators=[jobs.validators.validate_image_extension])),
                ('facebook_link', models.CharField(blank=True, default='', max_length=300)),
                ('twitter_link', models.CharField(blank=True, default='', max_length=300)),
                ('instagram_link', models.CharField(blank=True, default='', max_length=300)),
                ('location_donate', models.CharField(blank=True, default='', max_length=300)),
                ('email_donate', models.CharField(blank=True, default='', max_length=300)),
                ('phone_donate', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GetInvolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_careers_getinvolved', models.FileField(blank=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('text_careers_getinvolved', models.CharField(blank=True, default='', max_length=300)),
                ('image_joinus_getinvolved', models.FileField(blank=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('text_joinus_getinvolved', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_about_index', models.FileField(blank=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension])),
                ('text_about_index', models.TextField(blank=True, default='', max_length=1000)),
                ('image_story_index', models.FileField(blank=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension])),
                ('text_story_index', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_text', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image_index', models.FileField(blank=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension])),
                ('slide_title_index', models.CharField(blank=True, default='', max_length=300)),
                ('slide_subtitle_index', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VisionMissionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vission_Mission_Value_desc1', models.CharField(blank=True, default='', max_length=300)),
                ('Vission_Mission_Value_desc2', models.CharField(blank=True, default='', max_length=300)),
                ('vission_text', models.CharField(blank=True, default='', max_length=300)),
                ('mission_text', models.CharField(blank=True, default='', max_length=300)),
                ('value_text', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_volunteer', models.FileField(upload_to='background/volunteer/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeAreDoingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatDoDetail_image_gallery', models.FileField(blank=True, upload_to='background/WhatWeAreDoingDetails/', validators=[jobs.validators.validate_image_extension])),
                ('whatDoDetail_image1', models.FileField(blank=True, upload_to='background/WhatWeAreDoingDetails/', validators=[jobs.validators.validate_image_extension])),
                ('whatDoDetail_image2', models.FileField(blank=True, upload_to='background/WhatWeAreDoingDetails/', validators=[jobs.validators.validate_image_extension])),
                ('whatDoDetail_image3', models.FileField(blank=True, upload_to='background/WhatWeAreDoingDetails/', validators=[jobs.validators.validate_image_extension])),
                ('whatDoDetail_icon_name', models.CharField(blank=True, default='', max_length=300)),
                ('whatDoDetail_name', models.CharField(blank=True, default='', max_length=300)),
                ('whatDoDetail_desc1', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_desc2', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_desc3', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_desc4', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_desc5', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_desc6', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_desc7', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhoWeAre_image1', models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhoWeAre_image2', models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhoWeAre_image3', models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhoWeAre_desc1', models.TextField(blank=True, default='', max_length=1000)),
                ('WhoWeAre_desc2', models.TextField(blank=True, default='', max_length=1000)),
                ('WhoWeAre_desc3', models.TextField(blank=True, default='', max_length=1000)),
                ('WhoWeAre_desc4', models.TextField(blank=True, default='', max_length=1000)),
                ('WhoWeAre_desc5', models.TextField(blank=True, default='', max_length=1000)),
                ('WhoWeAre_desc6', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
