# Generated by Django 3.2.5 on 2021-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinvolved',
            name='text_careers_getinvolved',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='text_joinus_getinvolved',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
