# Generated by Django 3.2.5 on 2021-08-31 20:27

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210831_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image_bg_contact',
            field=models.FileField(default=7, upload_to='background/contact/', validators=[jobs.validators.validate_image_extension]),
            preserve_default=False,
        ),
    ]
