# Generated by Django 3.2.5 on 2021-09-03 07:51

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_contact_image_bg_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinvolved',
            name='image_bg_getInvolved',
            field=models.FileField(blank=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
