# Generated by Django 3.2.5 on 2021-09-03 07:58

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_getinvolved_image_bg_getinvolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionmissionvalue',
            name='image_bg',
            field=models.FileField(default=17, upload_to='background/vission_mission/', validators=[jobs.validators.validate_image_extension]),
            preserve_default=False,
        ),
    ]
