# Generated by Django 3.2.5 on 2021-09-03 08:17

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_visionmissionvalue_image_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='image_bg_whoweare',
            field=models.FileField(blank=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
