# Generated by Django 3.2.7 on 2021-09-05 18:30

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_whoweare_image_bg_whoweare'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeAreDoingBackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image_what_we_are_doing', models.FileField(blank=True, default='', upload_to='background/WhatWeAreDoing/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
