# Generated by Django 3.2.7 on 2021-09-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_whatwearedoingbackgroundimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc5',
        ),
        migrations.RemoveField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc6',
        ),
        migrations.RemoveField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc7',
        ),
        migrations.RemoveField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_image1',
        ),
        migrations.RemoveField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_image2',
        ),
        migrations.RemoveField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_image3',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='WhoWeAre_desc5',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='WhoWeAre_desc6',
        ),
    ]
