# Generated by Django 3.2.7 on 2021-09-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210905_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image_bg_contact',
        ),
    ]
