# Generated by Django 3.2.7 on 2021-09-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionmissionvalue',
            name='value_text',
        ),
        migrations.AddField(
            model_name='about',
            name='text_about1_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='about',
            name='text_about2_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='about',
            name='text_about3_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='about',
            name='text_about4_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='about',
            name='text_about_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='donate',
            name='location_donate_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='getinvolved',
            name='text_careers_getinvolved_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='getinvolved',
            name='text_joinus_getinvolved_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='index',
            name='text_about_index_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='index',
            name='text_story_index_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='index',
            name='whatDoDetail_text_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='slider',
            name='slide_subtitle_index_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slider',
            name='slide_title_index_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='visionmissionvalue',
            name='Vission_Mission_Value_desc1_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='visionmissionvalue',
            name='Vission_Mission_Value_desc2_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='visionmissionvalue',
            name='mission_text_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='visionmissionvalue',
            name='vission_text_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc1_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc2_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc3_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc4_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_name_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc1_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc2_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc3_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc4_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
