# Generated by Django 3.2.7 on 2021-12-06 12:14

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210930_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_volunteer', models.FileField(upload_to='background/volunteer/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
