# Generated by Django 3.2.5 on 2021-08-29 20:06

import blogs.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs_image', models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('blogs_date', models.DateField(blank=True, default=datetime.date.today)),
                ('blogs_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('blogs_location', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StoryAndBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_stories', models.FileField(blank=True, default='', upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension])),
                ('text_bg_stories', models.CharField(blank=True, default='', max_length=300)),
                ('image_bg_blogs', models.FileField(blank=True, default='', upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension])),
                ('text_bg_blogs', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_image_one', models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('story_image_two', models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('story_image_three', models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('story_date', models.DateField(blank=True, default=datetime.date.today)),
                ('story_location', models.CharField(blank=True, default='', max_length=300)),
                ('story_name', models.CharField(blank=True, default='', max_length=50)),
                ('story_desc1', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc2', models.CharField(blank=True, default='', max_length=300)),
                ('story_desc3', models.CharField(blank=True, default='', max_length=300)),
                ('story_desc4', models.CharField(blank=True, default='', max_length=300)),
                ('story_desc5', models.CharField(blank=True, default='', max_length=300)),
                ('story_desc6', models.CharField(blank=True, default='', max_length=300)),
                ('story_desc7', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['-story_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams_image', models.FileField(blank=True, upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
                ('teams_name', models.CharField(blank=True, default='', max_length=300)),
                ('teams_desc', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
