# Generated by Django 3.2.5 on 2021-08-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_storydetail_story_desc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc3',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc4',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc5',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc6',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc7',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
