# Generated by Django 3.2.5 on 2021-09-03 08:35

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_storydetail_story_desc1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bg_image_blog',
            field=models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
    ]
