# Generated by Django 3.2.5 on 2021-09-03 08:52

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_bg_image_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image_blog', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_stories', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_teams', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_career', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_career_details', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_about', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_contact', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_donate', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_getinvoloved', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_vission_mission', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_WhatWeareDoing', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_WhatWeareDoing_details', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_whoWeAre', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
                ('bg_image_storiyAndBlogs', models.FileField(blank=True, default='', upload_to='background/BackgroundImage/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
    ]
