# Generated by Django 3.2.5 on 2021-09-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_backgroundimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
    ]
