# Generated by Django 3.2.5 on 2021-09-03 17:24

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_delete_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bg_image_temas',
            field=models.FileField(blank=True, default='', upload_to='background/team/', validators=[blogs.validators.validate_image_extension]),
        ),
    ]
