# Generated by Django 3.2.7 on 2021-09-05 15:27

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_blog_blogs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image_temas', models.FileField(blank=True, default='', upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='bg_image_temas',
        ),
    ]
