# Generated by Django 3.2.7 on 2021-09-05 16:16

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20210905_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBGImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_teams', models.FileField(upload_to='background/volunteer/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
        migrations.DeleteModel(
            name='TeamBackgroundImage',
        ),
    ]
