# Generated by Django 3.2.7 on 2021-09-05 16:31

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20210905_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image_temas', models.FileField(blank=True, default='', upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
        migrations.DeleteModel(
            name='TeamBGImage',
        ),
    ]
