# Generated by Django 3.2.7 on 2021-09-05 19:01

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20210905_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image_story', models.FileField(blank=True, default='', upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
    ]
