# Generated by Django 3.2.7 on 2021-09-08 12:29

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_storybackgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyandblog',
            name='bg_image_story_bloag',
            field=models.FileField(blank=True, default='', upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
    ]
