# Generated by Django 3.2.7 on 2021-09-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_storyandblog_bg_image_story_bloag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogs_desc_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogs_location_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogs_title_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='storyandblog',
            name='text_bg_blogs_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='storyandblog',
            name='text_bg_stories_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_desc1_ar',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_desc2_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_desc3_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_desc4_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_desc5_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_desc6_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_desc7_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_location_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='storydetail',
            name='story_name_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='team',
            name='teams_desc_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='teams_name_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
